### ISSUE TITLE
Very close.. 

### ISSUE THREAD

**Issue by mitchiru** [insolite/gitlab-time-report#1]
I set it up running but effectively the hours spent are not displayed.

![screen shot 2017-10-03 at 10 33 28](https://user-images.githubusercontent.com/892231/31116496-9859cf36-a826-11e7-9cb0-9e6380519cd7.png)
![screen shot 2017-10-03 at 10 33 06](https://user-images.githubusercontent.com/892231/31116495-985711c4-a826-11e7-99c7-ff4aa98f6a35.png)

I'm not familiar with react, thats why I couldn't debug it deeper. But looks like a lot is working well except the data adapter?

**Comment by insolite** [comment]
Spent hours are fetched after fetching issues since GitLab API does not provide time fields in issue response data in any way at the moment. But I see there is even no issues count data, so that looks like the pagination issue I was experiencing recently. The GitLab API provides pagination with max 100 items per page. It's kinda difficult to implement pagination using `react-trunk` so I'm thinking about migrating to some kind of "pure promise middleware" and implement pagination support from scratch. So some issues might be lost at the moment if they are not filtered enough.

**Comment by insolite** [comment]
As a partial temporary solution, you may try to apply filters and press "refresh" or reload page (with URL query string args). Then data should be fetched with filters initially and if resulting issues count is less than 100, everything should display properly. I hope I'll fix it in a week or so.

**Comment by mitchiru** [comment]
Thx for feedback!

I tried the filters and also the pagination is not an issue since I have only one ticket with spend time. But even with filters on it fires about 145 requests.

I can see the only ticket available within the filtered project - but still no time reportings

![screen shot 2017-10-03 at 12 53 51](https://user-images.githubusercontent.com/892231/31121830-04713db8-a83a-11e7-91d8-f4737d93d706.png)

**Comment by mitchiru** [comment]
You can have my config.jsx :-)

export const GITLAB_URL = 'http://tglc.de:81';
export const PRIVATE_TOKEN = 'u7F5egDgLZBny8zStX89';

redbulll winglab is the project where is one issue at my name, which should have an spend time of 5m

**Comment by mitchiru** [comment]
btw pull fixed the 145 requests but issues are now gone.

**Comment by insolite** [comment]
Wow, thanks a lot! I see two projects with the same name (`39` and `41` IDs). Can it be a reason for disappeared issues? I've selected both of them and see the issue you mentioned before from `39`th project. Also time stats are OK.

`http://127.0.0.1:3030/#{"projects":[39,41],"members":[3]}`:
![time-report](https://user-images.githubusercontent.com/1101526/31127755-646b9d26-a858-11e7-9b53-d8764fac8a89.png)

**Comment by mitchiru** [comment]
wow. 

hm there is def only one project with this name. maybe one deleted?

**Comment by insolite** [comment]
Do you mean `archived` field? It's `false` for both. Btw `41`th is in another namespace.

**Comment by insolite** [comment]
I've implemented pagination support and also made time stats retrieving from `issues` response as it seems like they added a `time_stats` field to issues API in one of latest GitLab versions. So everything for your case should be OK now.
