### ISSUE TITLE
Configuration step?

### ISSUE THREAD

**Issue by slaivyn** [insolite/gitlab-time-report#2]
Hi!
I am trying to test gitlab-time-report but I can't find how to configure it properly. I have found a file name config.jsx but I don't know how to fill it.
I have my own gitlab instance, so I guess I should use its URL but what about the token? I could add an Application in Gitlab but it needs a callback URL and it provides two tokens appId and secretId.

**Comment by slaivyn** [comment]
Found it!
So it is a "personal token" which is created in the user's profile
Maybe this should be added in the REAMDE ;)

**Comment by insolite** [comment]
You're right. I will move it to the environment variables soon and will add a corresponding item. Thanks for suggestion.

**Comment by insolite** [comment]
Done https://github.com/insolite/gitlab-time-report/commit/cda791e825cc56ea5b805bcc8b0df3959275ed68
