### ISSUE TITLE
Some issues left out

### ISSUE THREAD

**Issue by fogs** [insolite/gitlab-time-report#3]
Hi there!

This tool is pretty much what I was looking for - thanks for thinking ahead and building it already :)

However, it seems to me that some issues are not considered when building the time report. So far I have found that issues are missing when:
- the issue is not assigned to anyone
- the issue is assigned to a user with the "External" flag

As someone who needs to fetch all times reported, I would at least expect a warning that there may be more issues that are currently not displayed. Even better would be, if those issues would actually be included in the report.

Again, thanks for this piece of code which is already very helpful!

fogs

**Comment by insolite** [comment]
Hi and thanks for reporting!

> the issue is not assigned to anyone

You're right, unassigned issues doesn't appear in table as it grouped by real users fetched from server which does not include any "no assignee" virtual member by default. However it would be useful to add it locally. By the way, "total" labels at the top should count not assigned issues if member filter is not applied. So this is the one more reason - reduce this implicitness and show not assigned issues in table too. I'll make it soon.

> the issue is assigned to a user with the "External" flag

Can't really reproduce it for myself. I checked "external" flag on user, changed assignee to him, even made user a Guest in that private project, but issue is still shown up in table and assigned to him. Maybe there is some difference in token access rights or gitlab versions? I'm using GitLab CE 10.0.1.
